<?php

namespace AppBundle\Repository;

/**
 * LoveImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoveImageRepository extends \Doctrine\ORM\EntityRepository
{
}
