<?php

namespace AppBundle\Repository;

/**
 * ProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class ProductionPictureRepository extends EntityRepository
{
    public function findAfterPicturesWhithMaxUpdateAt(){

        return $this->createQueryBuilder('p')
            ->select('MAX(p.updatedAt)','afterProduction.id')
            ->leftJoin('p.afterProduction','afterProduction')
            ->addSelect('afterProduction.id')
            ->where('afterProduction.id IS NOT NULL')
            ->groupBy('afterProduction.id')
            ->getQuery()
            ->getResult();

    }
}
