<?php

namespace AppBundle\Repository;

/**
 * ProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class ProductionPictureRepository extends EntityRepository
{
    public function findAfterPicturesWhithMaxUpdateAt(){

        return $this->createQueryBuilder('p')
            ->select('MAX(p.updatedAt)','afterProduction.id')
            ->leftJoin('p.afterProduction','afterProduction')
            ->addSelect('afterProduction.id')
            ->where('afterProduction.id IS NOT NULL')
            ->groupBy('afterProduction.id')
            ->getQuery()
            ->getResult();

    }

    public function findPicturesBeforeByProductionId($id){

        return $this->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('p.beforeProduction','beforeProduction')
            ->addSelect('beforeProduction.id')
            ->where('beforeProduction.id =:id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();

    }

    public function findPicturesAfterByProductionId($id){

        return $this->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('p.afterProduction','afterProduction')
            ->addSelect('afterProduction.id')
            ->where('afterProduction.id =:id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();

    }
}
